backend:
  image: docker
  services:
    - docker:dind
  before_script:
    - cd backend
  script:
    - docker build -f Dockerfile -t renatobritto/gces-ti2-back .
    - docker login -u renatobritto -p $DOCKERHUB_PASSWORD
    - docker push renatobritto/gces-ti2-back

frontend:
  image: docker
  services:
    - docker:dind
  before_script:
    - cd frontend
  script:
    - docker build -f Dockerfile -t renatobritto/gces-ti2-front .
    - docker login -u renatobritto -p $DOCKERHUB_PASSWORD
    - docker push renatobritto/gces-ti2-front

frontend-test:
  image: node:14
  before_script:
    - cd frontend
  script:
    - npm install
    - npm run test

backend-test:
  image: node:14
  before_script:
    - cd backend
  script:
    - npm install
    - npm i nodemon -g
    - npm run unittest
